### ISSUE TITLE
Add "Now playing" and "Queue" items to left menu in moped mopidy http client

### ISSUE THREAD

**Issue by MurzNN** [martijnboland/moped#71] opened 2017-06-07 09:36 UTC
Very often users need to look at current queue and now playing song, and there are no easy way to find this links in Moped. Please add "Now playing" and "Queue" items to left menu, like in musicbox_webclient interface.

**Comment by kingosticks** [comment] 2017-06-07 10:53
https://github.com/martijnboland/moped/issues/64

**Comment by kingosticks** [comment] 2017-06-07 10:55
Duplicate of #64 which states this is by design and is not happening.

**Comment by martijnboland** [comment] 2017-06-23 09:26
What @kingosticks says

**Closed as completed by martijnboland** 2017-06-23 09:26 UTC
